### ISSUE TITLE
fix(core-token-vesting): weird types required in query message

### ISSUE THREAD

**Issue by matthiasmatt** [NibiruChain/cw-nibiru#108]
The message query for the core-token-vesting has a start_after parameter which is an optional denom. This start_after is later used as a filter for the denom of the vesting contracts.

```rust
pub enum QueryMsg {
    VestingAccount {
        address: String,
        start_after: Option<Denom>,
        limit: Option<u32>,
    },
}
```

**Comment by Unique-Divine** [comment]
Already complete
