### ISSUE TITLE
feat(token-vesting): add manager list to core-token-vesting contract

### ISSUE THREAD

**Issue by k-yang** [NibiruChain/cw-nibiru#120]
Token vesting needs a 3rd party manager to allocate tokens to users, instead of the master admin having to do it. If the master admin does it, it needs to send a separate msg for each recipient, which is constrained when the master admin is a CW3 multisig contract. A 3rd party manager could be an individual account, making token allocation more efficient.

**Comment by Unique-Divine** [comment]
- Closed by #124
